### ISSUE TITLE
Performance issue with v1.17.0

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpbackup-s3-plugin#40]
Having run tests with Greenplum 5.x and 6.x with the latest s3 plugin 1.17.0 I have noticed a huge dropoff in restore performance.

Restores are streaming at a much lower rate and the process is hanging after 20 minutes

I've tried varying the parameters to no avail and run tests with different versions of gpbackup

Rolling back to 1.16.0 seems to fix all the issues

**Comment by shivzone** [comment]
In our internal experiments we noticed that wth table sizes in the range (10MB-3GB), setting `restore_multipart_chunksize` to 10MB is more optimal. Can you pass both the gpbackup gprestore flags you used as well.

**Comment by baileygm** [comment]
These are the settings we are using

  backup_max_concurrent_requests: 6
  backup_multipart_chunksize: 100M
  restore_max_concurrent_requests: 6
  restore_multipart_chunksize: 100M
  encryption: off

**Comment by baileygm** [comment]
our tables sizes vary from 1 MB to 217GB

**Comment by shivzone** [comment]
Just to clarify, no extra flags were passed during both gpbackup or gprestore (`--single-data-file` , `--no-compression`, `--include-table`, `--jobs`, etc) ?
Also, can you run `gprestore` by resetting `restore_multipart_chunksize` to 10MB. 
(Note: Also just to clarify make sure you use 10MB or 100MB and not 10M or 100M)

**Comment by baileygm** [comment]
That's correct, no other extra flags were passed

I'll try to retest with the setting you requested before the end of the week

**Comment by baileygm** [comment]
It appears that there were errors with my config so my tests were all using the default setting for restore_multipart_chunksize 

I have now fixed that and run some tests with restoration of a 40G schema

With S3 Plugin version 1.160.0
====================
chunk size =   5MB  time = 3m45s
chunk size = 10MB  time = 3m17s
chunk size = 100MB time = 4m10s

With S3 Plugin version 1.17.0
===================
chunk size =   5MB  time = 3m23s
chunk size = 10MB  time = 3m46s
chunk size = 20MB  time = 3m23s

I cannot draw any conclusions from these brief tests but I am surprised to see a much closer comparison in performance between the two plug versions

I will try to repeat the tests next week for our full system

**Comment by shivzone** [comment]
Yes please. In our internal experiments based on workloads switching chunk size have always helped out. You can start out with 500MB chunk size (which is most suited when average table size is large), and alter them to a lower number 10-50MB when your median table size is small (~1GB).
We do have a separate effort/feature where we plan to dynamically modify the chunk size based on the size of each table being backed up or restored. That will be made available in a future release

**Comment by shivzone** [comment]
@baileygm if you haven't noticed these issues anymore with configuration updates can I close this issue ?
