### ISSUE TITLE
s3 plugin doesn't work with s3-compatible storage

### ISSUE THREAD

**Issue by Stolb27** [greenplum-db/gpbackup-s3-plugin#61]
The latest changes from https://github.com/greenplum-db/gpbackup-s3-plugin/pull/9/commits/bce4362169dddc2ed81d84af95c6e3e7781065c6 break work with s3-compatible storage. The next error happens:

```
20231208:11:20:27 gpbackup:givi:samsung-ivanov:396025-[CRITICAL]:-exit status 1: 20231208:11:20:27 gpbackup_s3_plugin:givi:samsung-ivanov:396382-[ERROR]:-NoSuchBucket: The specified bucket does not exist.
        status code: 404, request id: b33f5d6b7077be48, host id:
```

because there is no bucket name in the url.

**Comment by woblerr** [comment]
We got the similar problem. It was unexpected after the plugin update.

**Comment by kyeap-vmware** [comment]
Fixed with https://github.com/greenplum-db/gpbackup-s3-plugin/pull/62.
